const skins = [
  'Army Sheen',
  'Lush Ruins',
  'Ancient Earth',
  'Jungle Dashed',
  'Night',
  'Tall Grass',
  'Panther Camo',
  'Ancient Ritual',
  'Silver',
  'Dark Water',
  'Dusk Ruins',
  'Carved Jade',
  'Blast From the Past',
  'Ancient Lore',
  'Gold Brick',
  'Ancient Visions',
  'Run and Hide',
  'Panthera onca',
  'Welcome to the Jungle',
  'Tornado',
  'Caramel',
  'Candy Apple',
  'Hot Rod',
  'Anodized Navy',
  'Bulldozer',
  'Fade',
  'Forest Leaves',
  'Jungle',
  'Lichen Dashed',
  'Jungle Spray',
  'Jungle Tiger',
  'Ossified',
  'Contractor',
  'Olive Plaid',
  'Green Plaid',
  'Green Plaid',
  'Sand Dune',
  'Traveler',
  'Leather',
  'Commuter',
  'Coach Class',
  'First Class',
  'Business Class',
  'Red Leather',
  'First Class',
  'Pilot',
  'Jet Set',
  'Urban DDPAT',
  'Army Sheen',
  'Forest DDPAT',
  'Army Sheen',
  'Forest DDPAT',
  'Bone Mask',
  'Carbon Fiber',
  'Caged Steel',
  'Silver',
  'Death Rattle',
  'Green Apple',
  'Tuxedo',
  'Meteorite',
  'Tuxedo',
  'Emerald Pinstripe',
  'Franklin',
  'Lab Rats',
  'Nuclear Waste',
  'Contamination',
  'Radiation Hazard',
  'Chemical Green',
  'Fallout Warning',
  'Hot Shot',
  'Reactor',
  'Setting Sun',
  'Bone Machine',
  'Nuclear Garden',
  'Toxic',
  'Styx',
  'Cerberus',
  'Indigo',
  'Navy Murano',
  'Canal Spray',
  'Boroque Sand',
  'Stone Mosaico',
  'Baroque Purple',
  'Candy Apple',
  'Orange Murano',
  'Dark Filigree',
  'Emerald',
  'Baroque Red',
  'Orange Filigree',
  'Violet Murano',
  'Red Filigree',
  'Baroque Orange',
  'Stained Glass',
  'Cinquedea',
  'The Prince',
  'Storm',
  'Indigo',
  'Indigo',
  'Storm',
  'Briar',
  'Royal Blue',
  'Green Apple',
  'Silver',
  'Rust Coat',
  'Chainmail',
  'Dark Age',
  'Hand Cannon',
  'Chalice',
  'Knight',
  'Dragon Lore',
  'Desert Storm',
  'Palm',
  'Predator',
  'Snake Camo',
  'Copperhead',
  'Copper',
  'Blaze',
  'Scorpion',
  'Brass',
  'Predator',
  'Sand Dashed',
  'Sand Spray',
  'Sand Mesh',
  'Sand Dune',
  'Desert Storm',
  'VariCamo',
  'Palm',
  'Orange Peel',
  'Safari Mesh',
  'Snake Camo',
  'VariCamo',
  'Brass',
  'Damascus Steel',
  'Amber Fade',
  'Amber Fade',
  'Sand Dune',
  'Walnut',
  'Gunsmoke',
  'Tornado',
  'Anodized Navy',
  'Brass',
  'Sand Dashed',
  'Sand Dune',
  'Colony',
  'Contractor',
  'Groundwater',
  'Candy Apple',
  'Stained',
  'Granite Marbleized',
  'Gunsmoke',
  'Boreal Forest',
  'CaliCamo',
  'Anodized Navy',
  'Candy Apple',
  'Full Stop',
  'Pit Viper',
  'Jungle Dashed',
  'Waves Perforated',
  'Sage Spray',
  'Storm',
  'Blue Spruce',
  'Boreal Forest',
  'Blue Steel',
  'Cyanospatter',
  'Night Ops',
  'Safari Mesh',
  'Mudder',
  'Anodized Navy',
  'Teardown',
  'Night Ops',
  'Cobalt Quartz',
  'Grassland',
  'Tornado',
  'Forest Leaves',
  'Grassland Leaves',
  'Modern Hunter',
  'Blaze Orange',
  'Modern Hunter',
  'Blaze Orange',
  'Modern Hunter',
  'Modern Hunter',
  'Splash Jam',
  'Hunting Blind',
  'Scorched',
  'Safari Mesh',
  'Colony',
  'Contractor',
  'Bone Mask',
  'Orange Peel',
  'Groundwater',
  'Gator Mesh',
  'Tropical Storm',
  'CaliCamo',
  'Hot Rod',
  'Blaze',
  'Amber Fade',
  'Bulldozer',
  'Irradiated Alert',
  'Irradiated Alert',
  'Irradiated Alert',
  'Fallout Warning',
  'Fallout Warning',
  'Fallout Warning',
  'Radiation Hazard',
  'Nuclear Threat',
  'Nuclear Threat',
  'Contrast Spray',
  'Winter Forest',
  'Arctic Camo',
  'Blizzard Marbleized',
  'Silver',
  'Whiteout',
  'Sage Spray',
  'Scorched',
  'Contrast Spray',
  'Storm',
  'Storm',
  'Urban DDPAT',
  'Gunsmoke',
  'Night',
  'Grassland',
  'Nitro',
  'Detour',
  'VariCamo Blue',
  'Pink DDPAT',
  'Road Rash',
  'Master Piece',
  'Contractor',
  'Army Recon',
  'Army Mesh',
  'Blue Spruce',
  'Contractor',
  'Orange Peel',
  'Condemned',
  'Forest Leaves',
  'VariCamo',
  'Gator Mesh',
  'VariCamo',
  'Teardown',
  'Silver Quartz',
  'Acid Fade',
  'Nitro',
  'Jungle',
  'Bamboo Garden',
  'Surfwood',
  'Seabird',
  'Jungle Thicket',
  'Dark Blossom',
  'Sunset Lily',
  'Rust Leaf',
  'Banana Leaf',
  'Teal Blossom',
  'Crimson Blossom',
  'Sundown',
  'Day Lily',
  'Midnight Lily',
  'Sea Calico',
  'Synth Leaf',
  'Wild Lily',
  'Wild Lotus',
  'Urban Dashed',
  'Polar Mesh',
  'Forest Night',
  'Polar Camo',
  'Colony',
  'Urban DDPAT',
  'Urban DDPAT',
  'Candy Apple',
  'Ash Wood',
  'Carbon Fiber',
  'Metallic DDPAT',
  'Metallic DDPAT',
  'Amber Fade',
  'Urban Rubble',
  'Red Quartz',
  'Urban Perforated',
  'Urban DDPAT',
  'Carbon Fiber',
  'Glacier Mesh',
  'Black Laminate',
  'Demolition',
  'Rust Coat',
  'Sweeper',
  'Mudder',
  'Slide',
  'Dirt Drop',
  'Candy Apple',
  'Calf',
  'Nitro',
  'High Beam',
  'Brake Light',
  'Hand Brake',
  'Check Engine',
  'Converter',
  'Vino Primo',
  'Fade',
  'Safety Net',
  'Twin Turbo',
  'Integrale',
  'Mandrel',
  'Facility Sketch',
  'Facility Dark',
  'Coolant',
  'Facility Draft',
  'Motherboard',
  'Bulkhead',
  'Cold Fusion',
  'Mainframe',
  'Exchanger',
  'Facility Negative',
  'Co-Processor',
  'Acheron',
  'wCore Breach',
  'Random Access',
  'Nuclear Garden',
  'Remote Control',
  'Control Panel',
  'Desert Brush',
  'Desert DDPAT',
  'Bleached',
  'Prey',
  'Parched',
  'Spalted Wood',
  'Old Roots',
  'Withered Vine',
  'Midnight Palm',
  'Black & Tan',
  'Quick sand',
  'New Roots',
  'Amber Fade',
  'Orange Anolis',
  'Red DDPAT',
  'Case Hardened',
  'Fade',
  'Death Strike',
  'Gold Arabesque',
  'Drought',
  'Anolis',
  'Navy Sheen',
  'Sienna Damask',
  'Prey',
  'Drift Wood',
  'CaliCamo',
  'Midnight Palm',
  'Verdant Growth',
  'Purple DDPAT',
  'Music Box',
  'Humidor',
  'Desert Blossom',
  'Elegant Vines',
  'Pink DDPAT',
  'Sand Storm',
  'Oxide Oasis',
  'Fennec Fox',
  'Desert Hydra',
  'Sputnik',
  'Fizzy POP',
  'Spring Twilly',
  'Amber Fade',
  'Full Stop',
  'Safety Net',
  'Blaze',
  'Syndicate',
  'POP',
  'Space Race',
  'Autumn Twilly',
  'Red Quartz',
  'Whiteout',
  'Propaganda',
  'Meltdown',
  'The Coalition',
  'Gamma Doppler',
  'Strats',
  'Faulty Wiring',
  'Blue Tire',
  'Framework',
  'Oil Change',
  'Red Tire',
  'Mechanism',
  'Carbon Fiber',
  'Breaker Box',
  'Green Laminate',
  'Schematic',
  'Interlock',
  'Infrastructure',
  'CAUTION!',
  'Prism Terrace',
  'Digital Architect',
  'Fall Hazard',
  'Hazard Pay',
  'Imminent Danger',
  'Army Sheen',
  'Army Sheen',
  'Impact Drill',
  'Seabird',
  'Night',
  'Urban Rubble',
  'Para Green',
  'Fade',
  'Whiteout',
  'Full Stop',
  'Nitro',
  'Emerald',
  'Bulldozer',
  'Duelist',
  'Twilight Galaxy',
  'Hot Rod',
  'Asterion',
  'Daedalus',
  'Moon in Libra',
  'Moon in Libra',
  'Hades',
  'Pathfinder',
  'Sun in Leo',
  'Shipping Forecast',
  "Minotaur's Labyrinth",
  "Pandora's Box",
  'Chronos',
  'Icarus Fell',
  'Poseidon',
  'Medusa',
  'Bamboo Print',
  'Bamboo Shadow',
  'Bamboo Forest',
  'Orange Kimono',
  'Mint Kimono',
  'Crimson Kimono',
  'Midnight Storm',
  'Aqua Terrace',
  'Counter Terrace',
  'Terrace',
  'Neon Kimono',
  'Sunset Storm 壱',
  'Sunset Storm 弐',
  'Daybreak',
  'Hydroponic',
  'Akihabara Accept',
  'Jungle DDPAT',
  'Tornado',
  'Dry Season',
  'Anodized Gunmetal',
  'Jungle',
  'Groundwater',
  'Sand Dune',
  'Mayan Dreams',
  'Palm',
  'Mosaico',
  'Facets',
  'Anodized Navy',
  'Hazard',
  'Rust Coat',
  'Spitfire',
  'Emerald',
  'Barricade',
  'Night Borre',
  'Scorched',
  'Tornado',
  'Red Stone',
  'Chainmail',
  'Moss Quartz',
  'Pathfinder',
  'Pyre',
  'Brass',
  'Emerald Quartz',
  'Copper Borre',
  'Frost Borre',
  'Astral Jörmungandr',
  'Flame Jörmungandr',
  'Emerald Jörmungandr',
  'Mjölnir',
  'Gungnir',
  'Surveillance',
  'Charter',
  'Army Sheen',
  'Forest Night',
  'Jungle Dashed',
  'Switch Board',
  'The Bronze',
  'Carbon Fiber',
  'Nitro',
  'Magna Carta',
  'Dispatch',
  'Threat Detected',
  'Global Offensive',
  'Prime Conspiracy',
  'Crime Scene',
  'Berries And Cherries',
  'Target Acquired',
  'Blue Phosphor',
  'Fade',
  'Death Rattle',
  'Heist',
  'Clay Ambush',
  'Predator',
  'Phoenix Chalk',
  'Vault Heist',
  'Phoenix Marker',
  'Houndstooth',
  'Rust Coat',
  'Tiger Pit',
  'Phoenix Stencil',
  'Night Heist',
  'Franklin',
  'Franklin',
  'Phoenix Blacklight',
  'Hypnotic',
  'Hot Snakes',
  'Silk Tiger',
  'X-Ray',
  'Skulls',
  'Ultraviolet',
  'Wings',
  'Dark Water',
  'Dark Water',
  'Dragon Tattoo',
  'Hypnotic',
  'Case Hardened',
  'Lightning Strike',
  'Faded Zebra',
  'Doomkitty',
  'Memento',
  'Orange DDPAT',
  'Splash',
  'Orange DDPAT',
  'Red Laminate',
  'BOOM',
  'Death by Kitty',
  'Tempest',
  'Black Limba',
  'Bone Pile',
  'Wave Spray',
  'Shattered',
  'Demeter',
  'Bright Water',
  'Zirka',
  'Graven',
  'Overgrowth',
  'Emerald Dragon',
  'Ocean Foam',
  'Graphite',
  'Golden Koi',
  'Fire Serpent',
  'Blue Titanium',
  'Blood Tiger',
  'Hexane',
  'Hive',
  'Crimson Web',
  'Case Hardened',
  'Hypnotic',
  'Graphite',
  'Hemoglobin',
  'Cold Blooded',
  'Serum',
  'Blood in the Water',
  'Cobalt Halftone',
  'Magma',
  'Kami',
  'Sandstorm',
  'Rising Skull',
  'Rose Iron',
  'Marina',
  'Pulse',
  'Redline',
  'Mehndi',
  'Guardian',
  'The Kraken',
  'Asiimov',
  'Blue Titanium',
  'Nightshade',
  'Water Sigil',
  'Ghost Camo',
  'Azure Zebra',
  'Steel Disruption',
  'Blue Laminate',
  'Blind Spot',
  'Afterimage',
  'Electric Hive',
  'Cobalt Disruption',
  'X-Ray',
  'Crimson Web',
  'Red FragCam',
  'Panther',
  'Stainless',
  'Blue Fissure',
  'Tread Plate',
  'Titanium Bit',
  'Heirloom',
  'Copper Galaxy',
  'The Fuschia Is Now',
  'Undertow',
  'Victoria',
  'Corporal',
  'Terrain',
  'Sandstorm',
  'Heaven Guard',
  'Heat',
  'Pulse',
  'Sergeant',
  'Guardian',
  'Redline',
  'Trigon',
  'Antique',
  'Asiimov',
  'Chameleon',
  'Isaac',
  'Slashed',
  'Retribution',
  'Kami',
  'Desert Warfare',
  'Poison Dart',
  'Twist',
  'Module',
  'Pulse',
  'Torque',
  'Antique',
  'Heaven Guard',
  'Curse',
  'Tatter',
  'Atomic Alloy',
  'Cyrex',
  'Orion',
  'Caiman',
  'Vulcan',
  'Desert-Strike',
  'Howl',
  'Urban Hazard',
  'Desert-Strike',
  'Ivory',
  'Abyss',
  'Labyrinth',
  'Osiris',
  'Tigris',
  'Koi',
  'Super',
  'Conspiracy',
  'Fowl Play',
  'Water Elemental',
  'Asiimov',
  'Cyrex',
  'Dark Water',
  'Ultraviolet',
  'Blood Tiger',
  'Hexane',
  'Bratatat',
  'Red Python',
  'Blue Streak',
  'Virus',
  'Ocean Foam',
  'Steel Disruption',
  'Crimson Web',
  'Bengal Tiger',
  'Bloomstick',
  'Corticera',
  'Corticera',
  'Bullet Rain',
  'Jaguar',
  'Murky',
  'Firestarter',
  'Dart',
  'Urban Hazard',
  'Delusion',
  'Grinder',
  'Basilisk',
  'Griffin',
  'Highwayman',
  'Cartel',
  'Cardiac',
  'Tranquility',
  'Wasteland Rebel',
  'Fire Elemental',
  'Catacombs',
  'System Lock',
  'Deadly Poison',
  'Grotto',
  'Quicksilver',
  'Urban Shock',
  'Naga',
  'Malachite',
  'Serenity',
  'Cartel',
  '龍王 (Dragon King)',
  'Muertos',
  "Man-o'-war",
  'Chatterbox',
  'Elite Build',
  'Armor Core',
  'Bronze Deco',
  'Valence',
  'Origami',
  'Worm God',
  'Heat',
  'Pole Position',
  'Grand Prix',
  'Monkey Business',
  'Eco',
  'Djinn',
  'Hyper Beast',
  'Neon Rider',
  'Rocket Pop',
  'Bunsen Burner',
  'Ranger',
  'Elite Build',
  'Riot',
  'Torque',
  'Neural Net',
  'Evil Daimyo',
  'Ruby Poison Dart',
  'Loudmouth',
  'Handgun',
  'Yellow Jacket',
  'Nemesis',
  'Cyrex',
  'Aquamarine Revenge',
  'Hyper Beast',
  'Dualing Dragons',
  'Survivor Z',
  'Wraiths',
  'Rangeen',
  'Cobalt Core',
  'Green Marine',
  'Scumbria',
  'Stone Cold',
  'Nebula Crusader',
  'Special Delivery',
  'Wingshot',
  'Frontside Misty',
  'Flux',
  'Big Iron',
  'Golden Coil',
  'Kill Confirmed',
  'Crimson Web',
  'Ricochet',
  'Corinthian',
  'Imperial',
  'Yorick',
  'Fuel Rod',
  'Retrobution',
  'Power Loader',
  'Tiger Moth',
  'Avalanche',
  'Teclu Burner',
  'Point Disarray',
  'The Executioner',
  'Shapewood',
  'Royal Paladin',
  'Fade',
  'Photic Zone',
  'Cartel',
  'Lapis Gator',
  'Necropos',
  'Jambiya',
  'Lead Conduit',
  'Valence',
  'Triumvirate',
  'Royal Legion',
  'Praetorian',
  'Impire',
  'Elite Build',
  'Kumicho Dragon',
  'Hyper Beast',
  'The Battlestar',
  'Fuel Injector',
  'Ventilators',
  'Orange Crash',
  'Spectre',
  'Bioleak',
  'Oceanic',
  'Atlas',
  'Fubar',
  'Firefight',
  'Red Astor',
  'Black Tie',
  'Ghost Crusader',
  'Re-Entry',
  'Primal Saber',
  'Asiimov',
  'Fleet Flock',
  "Chantico's Fire",
  'Judgement of Anubis',
  'Violent Daimyo',
  'Carnivore',
  'Exo',
  'Iron Clad',
  'Harvester',
  'Aerial',
  'Ice Cap',
  'Aristocrat',
  'Phobos',
  'Chopper',
  'Reboot',
  'Limelight',
  'Desolate Space',
  'Imperial Dragon',
  'Bloodsport',
  'Wasteland Rebel',
  'Mecha Industries',
  'Slipstream',
  'Briefing',
  'Grim',
  'Dazzle',
  'Ventilator',
  'Scumbria',
  'Imprint',
  'Triarch',
  'Powercore',
  'Petroglyph',
  'Weasel',
  'Directive',
  'Fuel Injector',
  'Airlock',
  'Syd Mead',
  'Neon Revolution',
  'Roll Cage',
  'Turf',
  'Sonar',
  'Sand Scale',
  'Black Sand',
  'Cirrus',
  'Ironwork',
  'Polymer',
  'Cyrex',
  'Gila',
  'Flashback',
  'Stinger',
  'Royal Consorts',
  'Wasteland Princess',
  'Shallow Grave',
  'Mecha Industries',
  'Buzz Kill',
  'Dragonfire',
  'Jungle Slipstream',
  'Blueprint',
  'Oxide Blaze',
  'Capillary',
  'Akoben',
  'Ripple',
  'Zander',
  'Crimson Tsunami',
  'Emerald Poison Dart',
  'Last Dive',
  'Scaffold',
  'Seasons',
  'Fever Dream',
  'Xiangliu',
  'Decimator',
  'Bloodsport',
  'Neo-Noir',
  'Blueprint',
  'Macabre',
  'Briefing',
  'Aloha',
  'Hard Water',
  'Cut Out',
  'Metal Flowers',
  'Orbit Mk01',
  'Woodsman',
  'Red Rock',
  'Death Grip',
  "Death's Head",
  'Cobra Strike',
  'Sugar Rush',
  'Hellfire',
  'Hyper Beast',
  'Oni Taiji',
  'Oceanic',
  'Morris',
  'Jungle Slipstream',
  'Capillary',
  'Triqua',
  'Hunter',
  'Cracked Opal',
  'Off World',
  'Goo',
  'Phantom',
  'Ziggy',
  'Exposure',
  'Tacticat',
  'High Roller',
  'Llama Cannon',
  'Leaded Glass',
  'The Empress',
  'See Ya Later',
  'Aloha',
  'Black Sand',
  'Oxide Blaze',
  'Urban Hazard',
  'Grip',
  'Flame Test',
  'Night Riot',
  'Wild Six',
  'Lionfish',
  'SWAG-7',
  'Arctic Wolf',
  'Moonrise',
  'Cortex',
  'Stymphalian',
  'Mortis',
  'Bloodsport',
  'Neo-Noir',
  'Shred',
  'Survivalist',
  'Capillary',
  'Amber Slipstream',
  'Snek-9',
  'Traction',
  'Warhawk',
  'Toy Soldier',
  'High Seas',
  'Powercore',
  'Eco',
  'PAW',
  'Eye of Athena',
  'Devourer',
  'Nightmare',
  'Code Red',
  'Neon Rider',
  'Modest Threat',
  'Oxide Blaze',
  'Wood Fired',
  'Magnesium',
  'Black Sand',
  'Danger Close',
  'Fubar',
  'Scavenger',
  'Signal',
  'Pipe Down',
  'Nevermore',
  'Flashback',
  'Momentum',
  'Mecha Industries',
  'Phosphor',
  'Asiimov',
  'Neo-Noir',
  'Crypsis',
  'Uncharted',
  'Whitefish',
  'Akoben',
  'Mischief',
  'Verdigris',
  'Off World',
  'Atheris',
  'Bamboozle',
  'Light Rail',
  'Gauss',
  'Moonrise',
  'Skull Crusher',
  'Momentum',
  'Incinegator',
  'Angry Mob',
  'The Emperor',
  'Flash out',
  'Assault',
  'Elite 1.6',
  'Popdog',
  'Classic Crate',
  'Decommissioned',
  'Sacrifice',
  'Aztec',
  'Buddy',
  'Plastique',
  'Inferno',
  'Agent',
  'Nostalgia',
  'Death by Puppy',
  'Hydra',
  'Commemoration',
  'Wildfire',
  'Plume',
  'Black Sand',
  'Memento',
  'Warbird',
  'Torn',
  'Acid Wash',
  'Balance',
  'Embargo',
  'Obsidian',
  'Neon Ply',
  'Arctic Wolf',
  'Rat Rod',
  'Decimator',
  'Bloodshot',
  'Colony IV',
  'Stalker',
  'Containment Breach',
  'Distressed',
  'Prototype',
  'Bone Forged',
  'Desert Strike',
  'Tom Cat',
  'Blue Ply',
  'Capillary',
  'Acid Etched',
  'Enforcer',
  'Apocalypto',
  'Dark Wing',
  'Fever Dream',
  'Justice',
  'Disco Tech',
  'Phantom Disruptor',
  'Player Two',
  'Bullet Queen',
  "Ol' Rusty",
  'Ultralight',
  'Gnarled',
  'Cassette',
  'Freight',
  'Runic',
  'Mainframe 001',
  'Monster Call',
  'Brother',
  'Connexion',
  'Kitbash',
  'Allure',
  'Entombed',
  'Vogue',
  'Tooth Fairy',
  'Legion of Anubis',
  'Printstream',
  'Digital Mesh',
  'Deep Relief',
  'Containment',
  'Vendetta',
  'Cocoa Rampage',
  'Vandal',
  'Condition Zero',
  'Gold Bismuth',
  'Dezastre',
  'Clear Polymer',
  'Parallax',
  'Exoskeleton',
  'Fairy Tale',
  'Monster Mashup',
  'Cyber Security',
  'Neo-Noir',
  'Printstream',
  'Oscillator',
  'Windblown',
  'O.S.I.P.R.',
  'Circaetus',
  'Junk Yard',
  'Heavy Metal',
  'Clear Polymer',
  'dev_texture',
  'Button Masher',
  'Cyber Shell',
  'Trigger Discipline',
  'Slate',
  'XOXO',
  'Chromatic Aberration',
  'Food Chain',
  'In Living Color',
  'The Traitor',
  'Plague',
  'Tread',
  'Keeping Tabs',
  'Guerrilla',
  'Lumen',
  'Black Lotus',
  'Watchdog',
  'BI83 Spectrum',
  'ZX Spectron',
  'Boost Protocol',
  'Mount Fuji',
  'Spider Lily',
  'Toybox',
  'Snack Attack',
  'Turbo Peek',
  'Leet Museo',
  'Ocean Drive',
  'Scrawl',
  'Ensnared',
  'Foresight',
  'Necro Jr.',
  'Lifted Spirits',
  'Poultrygeist',
  'Spirit Board',
  'Space Cat',
  'Dream Glade',
  'Night Terror',
  'Zombie Offensive',
  'Ticket to Hell',
  'Melondrama',
  'Rapid Eye Movement',
  'Abyssal Apparition',
  'Nightwish',
  'Starlight Protector',
  'Drop Me',
  'Destroyer',
  'Roadblock',
  'Monkeyflage',
  'Meow 36',
  'Winterized',
  'Poly Mag',
  'Downtown',
  'Vent Rush',
  'Flora Carnivora',
  'Dragon Tech',
  'Crazy 8',
  'Visions',
  'Kiss♥Love',
  'Ice Coaled',
  'Chromatic Aberration',
  'Printstream',
];
const armas = [
  'P250',
  'CZ75-Auto',
  'Dual Berettas',
  'Desert Eagle',
  'R8 Revolver',
  'P2000',
  'USP-S',
  'Five-SeveN',
  'Tec-9',
  'Glock-18',
  'AWP',
  'SCAR-28',
  'SSG 08',
  'AUG',
  'M4A1-S',
  'M4A4',
  'FAMAS',
  'G3SG1',
  'SG 553',
  'AK-47',
  'Galil AR',
  'MP5-SD',
  'P90',
  'UMP-45',
  'MP7',
  'PP-Bizon',
  'MP9',
  'MAC-10',
  'XM1014',
  'Nova',
  'MAG-7',
  'Sawed-Off',
  'M249',
  'Negev',
];
exports.skins = skins;
exports.armas = armas;
